name: Java app build
on: 
  push:
    branches:
      - "master"
  pull_request:
    branches: [ master ]

jobs:
  Java-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Git checkout the repo
      - name: setup build env
        uses: actions/setup-java@v4
        with:
          java-version: 1.8
      - name: Grant access to to gradlew
        run: chmod +x gradlew
      - name: Build with gradle
        run: ./gradlew build
        
       

    