name: Java app build
on: 
  push:
    branches:
      - "githubaction"
  # pull_request:
  #   branches: [ master ]

jobs:
  Java-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Git checkout the repo
      - name: setup build env
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant access to to gradlew
        run: chmod +x gradlew
      - name: Build with gradles
        run: ./gradlew build
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yasantha1995/demo-app:${{ github.run_id }}
#      - name: replace deployment file with new tag

      
        
       

    